# Generated by Django 5.0.2 on 2026-05-07 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Номер партии')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Количество получено')),
                ('quantity_remaining', models.PositiveIntegerField(verbose_name='Остаток в партии')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('received_date', models.DateField(verbose_name='Дата получения')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['received_date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=10, verbose_name='Тип транзакции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общая стоимость')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='Партия')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Транзакция склада',
                'verbose_name_plural': 'Транзакции склада',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'received_date'], name='inventory_b_product_9c731f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', '-transaction_date'], name='inventory_s_product_e2f4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['batch', '-transaction_date'], name='inventory_s_batch_i_fd4cd9_idx'),
        ),
    ]
