# Generated by Django 6.0.5 on 2026-05-06 03:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('account_type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Обязательство'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип счёта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('customer', 'Клиент'), ('supplier', 'Поставщик'), ('both', 'Клиент и поставщик')], default='both', max_length=20, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('bin_optional', models.CharField(blank=True, max_length=20, verbose_name='БИН/ИИН (демо)')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('inventory_supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_counterparty', to='inventory.supplier', verbose_name='Связь с поставщиком склада')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
            ],
            options={
                'verbose_name': 'Фискальный период',
                'verbose_name_plural': 'Фискальные периоды',
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_fiscal_period')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('is_posted', models.BooleanField(default=True, verbose_name='Проведена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Журнал проводок',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('kind', models.CharField(choices=[('customer_receipt', 'Поступление от клиента'), ('supplier_payment', 'Оплата поставщику'), ('misc_income', 'Прочий приход'), ('misc_expense', 'Прочий расход')], max_length=30, verbose_name='Тип операции')),
                ('cash_account', models.CharField(choices=[('1010', 'Касса (1010)'), ('1030', 'Расчётный счёт (1030)')], default='1010', max_length=10, verbose_name='Деньги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_operations', to='accounting.counterparty', verbose_name='Контрагент')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operation', to='accounting.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Касса/банк',
                'verbose_name_plural': 'Касса и банк',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Кредит')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Счёт')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.counterparty', verbose_name='Контрагент')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Строка проводки',
                'verbose_name_plural': 'Строки проводок',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведён')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='accounting.counterparty', verbose_name='Поставщик')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice', to='accounting.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена закупки за ед.')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.purchaseinvoice', verbose_name='Документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка закупки',
                'verbose_name_plural': 'Строки закупки',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведён')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='accounting.counterparty', verbose_name='Покупатель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice', to='accounting.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Реализация',
                'verbose_name_plural': 'Реализации',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена продажи за ед.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Для демо; можно отличать от цены продажи.', max_digits=14, verbose_name='Себестоимость за ед.')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.salesinvoice', verbose_name='Документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка реализации',
                'verbose_name_plural': 'Строки реализации',
            },
        ),
    ]
